import {Geist, Geist_Mono} from "next/font/google";
import "./shadcn/tailwind.css";
import Menu from "@/components/ui/Menu";
import {ThemeProvider} from "next-themes";
import {Toaster} from "sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
            suppressHydrationWarning
        >
        <body className="h-full">

        <ThemeProvider attribute="class" defaultTheme="system" enableSystem >
            <div className="flex">
                <Menu/>
                <main className="flex-1 overflow-y-auto">
                    {children}
                    <Toaster position="top-right" richColors closeButton />

                </main>
            </div>
        </ThemeProvider>

        </body>
        </html>
    );
}
