import {Geist, Geist_Mono} from "next/font/google";
import "./shadcn/tailwind.css";
import NavBar from "@/components/ui/NavBar";
import Menu from "@/components/ui/Menu";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="h-full">
        <div className="flex flex-col h-full">
            {/*<NavBar />*/}
            <div className="flex flex-1 overflow-hidden">
                <Menu />
                <main className="flex-1 overflow-y-auto">
                    {children}
                </main>
            </div>
        </div>
        </body>
        </html>
    );
}
